### ISSUE TITLE
它似乎没法在1.13.2的服务端上运行

### ISSUE THREAD

**Issue by FrankHan052176** [TISUnion/PlayerInfoAPI#4]
[MCDR.log](https://github.com/TISUnion/PlayerInfoAPI/files/5413618/MCDR.log)
它似乎没法在1.13.2的carpet服务端上运行

**Comment by Fallen-Breath** [comment]
请详细说明服务端类型，你使用的插件种类，PlayerInfoAPI调用方法等有助于复现的步骤

**Comment by FrankHan052176** [comment]
服务器类型carpet-1.13.2
调用方法：
result = PlayerInfoAPI.getPlayerInfo(server,info.player)
position = result["Pos"]
然后就会出现（/data命令正常执行了，貌似是api没法返回坐标列表导致的）
[MCDR] [2020-10-21 14:25:40] [PT2-on_user_info@heredemo/ERROR]: Error calling on_user_info in plugin heredemo
Traceback (most recent call last):
  File "E:\MCDReforged-0.9.6\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\heredemo.py", line 11, in on_user_info
    position = result["Pos"]
TypeError: 'NoneType' object is not subscriptable
这样的报错

**Comment by Fallen-Breath** [comment]
请列出完整的调用方法而非局部代码

**Comment by FrankHan052176** [comment]
from imp import load_source
PlayerInfoAPI = load_source('PlayerInfoAPI', './plugins/PlayerInfoAPI.py')

def on_Info(server, info):
  HIGHLIGHT_ENABLE = True
  dimension_convert = {"0":"主世界","-1":"地狱","1":"末地"}
  if info.content =='!!here':
    result = PlayerInfoAPI.getPlayerInfo(server,info.player)
    position = result["Pos"]
    dimension = str(result["Dimension"])
    position_show = "["+str(int(position[0]))+","+str(int(position[1]))+","+str(int(position[2]))+"]"
    server.say("§e" + info.player + "§r 在 §2" + dimension_convert[dimension] + position_show + "§r 向各位打招呼")
    if(HIGHLIGHT_ENABLE):
      server.execute("effect give "+ info.player + " minecraft:glowing 15 1 true")
      server.tell(info.player,"您将会被高亮15秒")
这是here-newapi的代码（我改了一下事件，不然没有回应）

**Comment by Fallen-Breath** [comment]
请仔细阅读readme
